### ISSUE TITLE
Buscar intimações do EPROC 2G

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-fetcher#10]
# Contexto

Atualmente o sistema só busca intimações EPROC 1G, gostariamos que o sistema também sincronizasse intimações do EPROC 2G.

# Proposta

- Agendar consultas para o EPROC 2G no fetcher. 
- Identificar se a intimação é um 1G ou 2G nos dados salvos no banco.
- Adicionar em todos os registros da base de dados a identificação que a intimação é 1G (visto que todos os que estão na base são 1G).
- Adicionar o sistema na visualização do usuário e na geração de relatório.

# Definition of Done

Que seja possível visualizar intimações 1G e 2G no sistema, inclusive no CSV exportado e na tabela do usuário.

**Comment by zaiosc-dpers** [comment]
Verificando em Testes...

**Comment by zaiosc-dpers** [comment]
Devido ao filtro por data no SIE, ainda não foi possível visualizar intimações 2G no front.

Contudo, vale salientar que no caso do 2G não exibimos o nome do órgão julgador (ex.: Gab. Des. Armínio José Abreu Lima da Rosa), e sim o nome do órgão colegiado (ex.: 21ª Câmara Cível).

OBS.: Informações extraídas do aviso 202405158000028.
