### ISSUE TITLE
Verificar questão da data de disponibilização

### ISSUE THREAD

**Issue by marcelogm** [DefensoriaPublicaRS/sie-fetcher#3]
# Contexto

Ao buscar um lote de intimações na interop, um dos campos que são retornados é o campo de data de disponibilização. Precisamos saber o que isso significa. Parece ser a data em que consultamos aquilo pela primeira vez. Isso não seria util para a gente.

# Proposta

Verificar se da data de disponbilização que vem da API

# Definition of Done

Que saibamos a data que o evento foi expedido e não a data que consultamos algo.

**Comment by marcelogm** [comment]
Verificar intimação de id aviso com id 202405103003800.

**Comment by marcelogm** [comment]
> Verificar intimação de id aviso com id 202405103003800.
asdasd

**Comment by zaiosc-dpers** [comment]
> Verificar intimação de id aviso com id 202405103003800.

Opa, consegue pra gente o evento relacionado a essa intimação?
Pois na consulta processual a última intimação daquela parte aparece como sendo no evento 203, de 29/04/2024 18:48:51. 😕 
E o evento mais recente (210) é de 09/05, não tem nada pra 10/05 (até o momento, pelo menos).

![image](https://github.com/DefensoriaPublicaRS/sie-fetcher/assets/169402696/b90faa3a-a167-4160-ad41-15cdf405dad8)

![image](https://github.com/DefensoriaPublicaRS/sie-fetcher/assets/169402696/4487ea7b-9977-4977-8d6b-edfb9f769d23)

**Comment by marcelogm** [comment]
Formato do payload salvo na base. @zaiosc-dpers pode usar como referencia pros campos que vamos exibir pro usuario.

```json
{
  "_id": {
    "$oid": "663db82f0fc8d258187cab36"
  },
  "idAviso": "202405103003800",
  "__v": 0,
  "createdAt": {
    "$date": "2024-05-10T06:01:19.142Z"
  },
  "lastUpdate": {
    "$date": "2024-05-10T19:28:29.213Z"
  },
  "payload": {
    "id": "202405103003800",
    "tipo": "URG",
    "destinatario": {
      "nome": "NOME_DO_INTIMADO",
      "numeroDocumentoPrincipal": "DOCUMENTO_INTIMADO",
      "tipoPessoa": "fisica"
    },
    "processo": {
      "numero": "NUMERO_DO_PROCESSO",
      "competencia": "501",
      "classeProcessual": "7",
      "nivelSigilo": "1",
      "intervencaoMP": "false",
      "tamanhoProcesso": "45854545",
      "dataAjuizamento": "DATA_AJUIZAMENTO",
      "outros": {
        "rito": "2",
        "ritoProcessual": "Ordinário",
        "assuntoPrincipal": "5802",
        "dataAutuacao": "DATA_ATUACAO",
        "situacao": "MOVIMENTO"
      }
    },
    "orgao": {
      "codigoOrgao": "CODIGO_ORGAO_JULGADOR",
      "nomeOrgao": "NOME_DO_ORGAO_JULGADOR",
      "instancia": "ORIG",
      "codigoMunicipioIBGE": "CODIGO_IBGE"
    },
    "data": "20240510030000",
    "outros": {
      "identificadorMovimento": "203",
      "descricaoMovimento": "Expedida/certificada a intimação eletrônica",
      "dataHoraMovimento": "20240429184851",
      "codigoMovimento": "540400402",
      "codigoCNJ": "12265",
      "prazo": "5",
      "status": "Aberto",
      "inicioPrazo": "20240521000000",
      "finalPrazo": "20240527235959"
    }
  },
  "type": "URG"
}
```

**Comment by marcelogm** [comment]
@zaiosc-dpers parece que é isso mesmo né? Interop que está respondendo uma data errada, não?

Se for o caso, pode fechar a issue.

**Comment by zaiosc-dpers** [comment]
> @zaiosc-dpers parece que é isso mesmo né? Interop que está respondendo uma data errada, não?
> 
> Se for o caso, pode fechar a issue.

@marcelogm  Isso, atualmente aquela informação não é confiável nem mesmo para o que seria o seu propósito (sabermos quando o aviso foi parar na interop). 😞 

Fechando a issue...
