### ISSUE TITLE
Analisar como mostrar o nome do município

### ISSUE THREAD

**Issue by hbribeiro77** [DefensoriaPublicaRS/sie-fetcher#9]
# Contexto:

A ideia é que ao invés de mostrarmos o código IBGE do município (codigoMunicipioIBGE), mostremos o seu nome.

# Proposta

Aparentemente o IBGE tem serviço que faz isso: https://servicodados.ibge.gov.br/api/v1/localidades/municipios/4300604

![Image](https://github.com/DefensoriaPublicaRS/sie-front/assets/39736227/84772fb0-e591-4214-bda2-2269679300e1)

_Fonte: https://servicodados.ibge.gov.br/api/docs/localidades#api-Municipios-municipiosMunicipioGet_

Analisar se vamos buscar pra gerar o relatorio, se buscamos no job que persiste o negocio ou se criamos um job a parte pra pesquisar...
https://github.com/DefensoriaPublicaRS/sie-front/issues/13#issuecomment-2105252498

# Definition of done

Caso haja viabilidade técnica:
- Definição da estratégia
- Criação das tarefas técnicas

Não havendo viabilidade técnica:
- nada.

**Comment by zaiosc-dpers** [comment]
Verificando em Testes...
